name: odin

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/odin.yaml
      - odin/**

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - .github/workflows/odin.yaml
      - odin/**

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pwgen
            asset_name: pwgen-linux-amd64.tar.gz
          - os: windows-latest
            artifact_name: pwgen.exe
            asset_name: pwgen-windows-amd64.zip
          - os: macos-latest
            artifact_name: pwgen
            asset_name: pwgen-macos-arm64.tar.gz

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    timeout-minutes: 30

    concurrency:
      group: ${{ github.ref_name != 'main' && format('{0}-{1}-{2}', github.workflow, github.ref, matrix.os) || github.sha }}
      cancel-in-progress: ${{ github.ref_name != 'main' }}

    defaults:
      run:
        working-directory: odin

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: odin

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev-2024-12

      - name: Build desktop
        shell: bash
        run: odin build . -out:${{ matrix.artifact_name }}

      - name: Compress binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
          else
            tar -czf ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
            pwd
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          draft: true
